# version
version: "1.0"

permalink: date

# site
title: "IotaSpencer"
email: ken@electrocode.net
description: ""
keywords: "iotaspencer"


github_username: IotaSpencer

# Markdown
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# paths
baseurl: "/"
url: "https://iotaspencer.me"


# paginate
paginate: 10
paginate_path: "page/:num"

# scss
sass:
  sass_dir: /assets/stylesheet
  style: :compressed

# jekyll
plugins:
  - jekyll-feed
theme: jekyll-theme-hacker
