#version
version: "1.0"

permalink: date

# 站点设置
title: "IotaSpencer"
email: ken@electrocode.net
description: ""
keywords: "iotaspencer"


github_username: IotaSpencer

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/"
url: "https://iotaspencer.me"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
  sass_dir: /assets/stylesheet
  style: :compressed

theme: jekyll-theme-hacker
