theme: bulma-clean-theme
# TODO: copy theme files to my part of the site and use them from there 
# so i can use bootstrap and bulmas prefixed classes together
title: "iotaspencer.me"
description: "A simple Jekyll site using the Bulma Clean Theme"
# description: The ramblings of a madman in a mad world
author: "Ken Spencer"
email: "me@iotaspencer.me"
disqus:
  shortname: "iotaspencerme"
feed: 
  tags: true
  categories:
    - "technology"
    - "gem"
    - 'ubuntu'
    - 'updates'
    - 'linux'
    - 'programming'
    - 'python'
    - 'ruby'
    - 'jekyll'
    - 'javascript'
    - 'html'
    - 'css'
    - 'web'
    - 'misc'
  path: /feed.xml
# name: IotaSpencer
# year: 2025
# my_age: 33
# # Url is currently only used only for the RSS feed in feed.xml
url: https://iotaspencer.me
show_sidebar: true
sass:
  silence_deprecations: ['import']
  quiet_deps: true
related_project_keys: ["technology", "gem"]
skip_related_projects: true

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
repository: IotaSpencer/iotaspencer.me
share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: true
  reddit: true
  bsky: true
social:
  github: IotaSpencer
  gitlab: IotaSpencer
  twitter: Ken_I_Spencer
  youtube1: "@iotaspencer"
  youtube2: "@iotaplays"
  bluesky: "@iotaspencer.me"
  rss: feed.xml
  steam: IotaSpencer
  tel: "14087824682"
  floss.social: "@iotaspencer"
  discord: "iotaspencer"
  linkedin: ken-iota-spencer
  stackoverflow: 3095971/iotaspencer         
# Google Analytics key, leave blank to ignore

google_analytics: "G-WPXPG4QVW6"
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:
permalink: /:year/:month/:day/:title/

autopages:
  enabled: true

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
pagination:
  enabled: true
  # The number of posts to show per page
  per_page: 3
  permalink: /page/:num/
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: shell
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
timezone: America/New_York
exclude: ["README.md", "LICENSE", "vendor/", "node_src", "*.map", ".gitignore", ".idea/", ".vscode/",
  "Gemfile*", "*.gemspec", ".sass-cache", "_resume.html", ".jekyll-cache", ".jekyll-metadata",
   ".DS_Store", "node_modules/", "package-lock.json", "yarn.lock", ".venv/", "bin/", "_old_dirs/"]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
  - jekyll-paginate-v2
#defaults:
#  -
#    scope:
#      path: "projects"
#      type: "pages"
#    values:
#      layout: "project"
#      author: "Mr. Hyde"
#      category: "project"
