source "https://rubygems.org"
gem "bulma-clean-theme"
gem 'jekyll', '4.4.1'
gem 'logger'
gem 'jekyll-feed'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-avatar'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-include-cache'
gem 'jekyll-asciinema'
gem 'jekyll-paginate-v2'
gem 'netrc'
