source "https://rubygems.org"
gem "bulma-clean-theme", '1.2.0'
gem 'jekyll', '4.4.1'
gem 'logger'
source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-avatar'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-include-cache'
gem 'jekyll-asciinema'
gem 'jekyll-paginate'
gem 'netrc'
