source "https://rubygems.org"
gem "bulma-clean-theme"
gem 'jekyll', git: 'https://github.com/IotaSpencer/jekyll', branch: 'IotaSpencer-update-terminal-table'
gem 'logger'
gem 'jekyll-feed'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-avatar'
gem 'jemoji'
gem 'jekyll-mentions'
gem 'jekyll-include-cache'
gem 'jekyll-asciinema'
gem 'jekyll-paginate-v2'
gem 'netrc'
gem 'mkmatter', :path => '/home/ken/repos/mkmatter'
